### ISSUE TITLE
Img info date-time display format

### ISSUE THREAD

**Issue by cbeng** [hbstack/gallery#29]
https://github.com/hbstack/gallery/blob/b79c95962c35882cf14cde5f06a65854ed93b467/layouts/partials/hb/modules/gallery/functions/img-info.html#L5-6

The current date-time display results in the end of the formatted date string running straight into the beginning of the formatted time string, making the combined date-time illegible. Inserting a non-breaking space or another delimiter between date and time makes it legible.

Before
![Screenshot 2023-04-25 181518](https://user-images.githubusercontent.com/3948101/234441668-455c1a69-7ac2-48f0-9d4c-6b9b23be3d4a.png)

After
![Screenshot 2023-04-25 181549](https://user-images.githubusercontent.com/3948101/234441678-b60bbd48-e6e3-4d2d-8ed7-bcffa8a23d4b.png)

**Comment by razonyang** [comment]
Thanks for reporting this issue, fixed since `github.com/hbstack/gallery`'s `v0.4.1`.
