### ISSUE TITLE
Support album hierarchy

### ISSUE THREAD

**Issue by pleasantone** [hbstack/gallery#83]
Allow hierarchical representation of gallery pages based upon directory structure:

```
gallery/
    event/
        <best of event images>
        day1/
            <day1 images>
        day2/
             <day2 images>
```

Currently gallery treats every page in the gallery as flat when displaying the top level page.

**Comment by razonyang** [comment]
If I'm understanding the requirement correctly, it should be already supported, you'll need to create `index.md` for each gallery folder. e.g. `gallery/event/day1/index.md`, `gallery/event/day2/index.md`.

```sh
 $ tree content/gallery/event
├── 2023-10-01
│   ├── 20230102000000.jpg
│   ├── ....jpg
│   └── index.md
└── 2023-12-25
    ├── 20220102000000.jpg
    ├── .....jpg
    └── index.md
```

![image](https://github.com/hbstack/gallery/assets/17720932/f05a8eaa-01f0-483d-a5f1-a4221710a6e7)

**Comment by pleasantone** [comment]
You are absolutely correct, my problem was using `event/_index.md` not `event/index.md` however, as you point out, it then shows every image in every subfolder of event/ flat.

Ideally, I'd like to see only the images in `event/` and treat every child folder of event/ as an album...
Does that make sense?

**Comment by razonyang** [comment]
> Ideally, I'd like to see only the images in `event/` and treat every child folder of event/ as an album...

I think it can be achieved by creating `_index.md` in the `event` folder to make it become a branch bundle.

![image](https://github.com/hbstack/gallery/assets/17720932/9e84dee2-b6a7-40e1-bd14-2786e3d6ee53)

Alternatively, create an another section other than the `gallery`, and specify the `type` as `gallery` on front matter of each content file.

```
// content/event/_index.md
---
title: Event
type: gallery
---
```

**Comment by razonyang** [comment]
Docs updated: https://hbstack.dev/modules/gallery/overview/#how-to-create-sub-galleries

**Comment by pleasantone** [comment]
The only thing left is, when we're at an upper level gallery page, how should we hierarchically navigate down to the branches below?  The top level gallery page still shows all galleries as flat, and there is no way (other than via URL) to move down the hierarchy.

**Comment by razonyang** [comment]
> The only thing left is, when we're at an upper level gallery page, how should we hierarchically navigate down to the branches below?

Yes, we need an navigation for sub-galleries. I got two ideas.

1. Make sub-galleries as album.
| Album1 | Sub-Gallery1 | Album2 |
| Sub-Gallery2 | Album3 |

2. Create an independent widget showing the sub-galleries.

Which one is better for users? Or do you have other idea?

**Comment by pleasantone** [comment]
I think the thing we should be looking for, should be analogous to hierarchical content in other sections, like docs?

Ideally we could also support the series taxonomy.

Basically, I want it to look like anything else that Hugo does, but there aren’t a lot of examples of multi level hierarchies.

**Comment by razonyang** [comment]
Seems abstract to me, do you have a similar example (screenshot, UI)?

**Comment by razonyang** [comment]
I believe that the #94 PR fixes it, let me know if it suit your need, I'll merge it later.

**Comment by pleasantone** [comment]
Sorry for the delay, tested, confirmed good, thank you!

**Comment by razonyang** [comment]
No problem.
