### ISSUE TITLE
feature request - selecting key image for a gallery?

### ISSUE THREAD

**Issue by pleasantone** [hbstack/gallery#99]
In the Hugo social media code, the image selected for a page, if not specified as "images" in frontmatter uses the first image that matches the "*feature*" glob.

It would be quite cool if the key image for a child of a branch page used the same logic as the [social media code](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/partials/_funcs/get-page-images.html).

By key image, I mean the image that shows up to represent the child album on the link to that album.

**Comment by razonyang** [comment]
> By key image, I mean the image that shows up to represent the child album on the link to that album.

Didn't get it, is this feature request is about using child album's images (highlight/key images are prefered) as the social images for _branch_ page?

For example, take `gallery/events` as example, 

```
gallery/events
  /day1
    image1.jpg
    index.md
  /day2
    key-img.jpg
    index.md
```

When sharing the `gallery/events` branch bundle page on social media, it should show up the `key-img.jpg` of `day2`?

**Comment by pleasantone** [comment]
No, I didn't describe it clearly, my apologies. It doesn't even really have anything to do with the SEO/social media code, just keeping the photo consistent recycling the existing logic.

```
gallery/events
  /day1
    image1.jpg
    index.md
  /day2
    key-img-featured.jpg
    index.md
```

When you view at gallery/events, the image we pick to represent the day2 child gallery should respect the existing convention of being listed in day2.Page.images (usually the first image), or should have "feature" somewhere in the filename. The existing logic looks for the first filename alphabetically.

**Comment by razonyang** [comment]
I think I get it, you mean the ablum's cover shown on gallery (parent). The most latest image (by date and title) will be used as the album cover, and you want to use first social images as the cover as the internal template does. Let me know if I understand correctly.

**Comment by pleasantone** [comment]
Perfect!

**Comment by razonyang** [comment]
Should be implemented by #102.

**Comment by pleasantone** [comment]
Tested confirmed, thanks!

**Comment by razonyang** [comment]
@pleasantone Thanks for your supporting, I couldn't find a way to send you a private message. Would you mind I listing your name on the thanks page on our website?

**Comment by pleasantone** [comment]
I don’t mind but also not necessary, just wanted to appreciate your work. Thanks again!
